using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Linq;
using System.Collections.Frozen;

namespace Content.Client.AWS.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyLogConsoleMenu : FancyWindow
{
    [Dependency] private readonly IClientEconomyManager _economyManager = default!;

    private EconomyLogConsoleBoundUserInterface Owner { get; set; }
    private FrozenDictionary<string, EconomyBankAccount> _accounts = default!;

    public EconomyLogConsoleMenu(EconomyLogConsoleBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        LogDetails.SelectMode = ItemList.ItemListSelectMode.None;

        Owner = owner;

        _accounts = _economyManager.GetAccounts().ToFrozenDictionary();

        FillList();

        FindAccount.OnTextEntered += OnTextEnteredAccount;
        FindLog.OnTextEntered += OnTextEnteredLog;

    }

    private void OnSelectAccount(ItemList.Item accountId)
    {
        LogDetails.Clear();

        var account = (accountId.Metadata! as EconomyBankAccount)!;

        if (account.Logs.Count == 0)
        {
            LogDetails.AddItem("No logs detected");
            return;
        }
        for (int i = account.Logs.Count - 1; i != -1; i--)
        {
            var item = account.Logs[i];
            LogDetails.AddItem("[" + item.Date.ToString("hh\\:mm\\:ss") + "] — " + item.Text);
        }
    }

    private void OnTextEnteredAccount(LineEdit.LineEditEventArgs eventArgs)
    {
        AccountList.Clear();
        var upText = eventArgs.Text.ToUpper();
        foreach (var (key, value) in _accounts)
        {
            var fieldName = FormFieldName(value);
            if (fieldName.Contains(upText))
            {
                var field = AccountList.AddItem(fieldName);
                field.Metadata = value;
                field.OnSelected += OnSelectAccount;
            }
        }
        if (AccountList.Count == 0)
        {
            AccountList.AddItem("No data acquired");
            return;
        }
        AccountList.SortItemsByText();
    }
    private void OnTextEnteredLog(LineEdit.LineEditEventArgs eventArgs)
    {

        if (!AccountList.GetSelected().Any())
        {
            LogDetails.Clear();
            LogDetails.AddItem("Error no select Account");
            return;
        }
        var accountId = AccountList.GetSelected().First();
        LogDetails.Clear();
        var upText = eventArgs.Text.ToUpper();

        var account = (accountId.Metadata! as EconomyBankAccount)!;

        for (int i = account.Logs.Count - 1; i != -1; i--)
        {
            var item = account.Logs[i];
            if (item.Text.Contains(upText))
                LogDetails.AddItem("[" + item.Date.ToString("hh\\:mm\\:ss") + "] — " + item.Text);
        }
    }

    private void FillList()
    {
        foreach (var (key, value) in _accounts)
        {
            var field = AccountList.AddItem(FormFieldName(value));
            field.Metadata = value;
            field.OnSelected += OnSelectAccount;
        }
        AccountList.SortItemsByText();
    }

    private string FormFieldName(EconomyBankAccount account)
    {
        return account.AccountID + " — " + account.AccountName;
    }
}
