using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client.AWS.Economy.UI.ManagementConsole.Tabs;

[GenerateTypedNameReferences]
public sealed partial class BonusTab : Control
{
    public BonusTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
}
