namespace Content.Shared.AWS.Skills;

public sealed partial class CharacterSkillComponent : Component
{
    [ViewVariables(VVAccess.ReadWrite)]
    public SkillContainer Container;    // should be autogenerated by different system

    [ViewVariables(VVAccess.ReadWrite)]
    public SkillContainer? ContainerUpgraded;
}
