using Robust.Shared.GameStates;

namespace Content.Shared.AWS.Skills;

[RegisterComponent, NetworkedComponent]
public sealed partial class CharacterSkillComponent : Component
{
    [ViewVariables(VVAccess.ReadWrite)]
    public SkillContainer Container;    // should be autogenerated by different system

    [ViewVariables(VVAccess.ReadWrite)]
    public SkillContainer? ContainerUpgraded;
}
